Edit
wolox-training/ff-net-core pull request #10
Opened 2019-05-09 19:48 UTC by ffasitella

### Summary

- Added a view to edit an existing movie
- Added get and post methods to MoviesController

### Trello card

[https://trello.com/c/YLPWQXAW/7-edici%C3%B3n](https://trello.com/c/YLPWQXAW/7-edici%C3%B3n)

2019-05-13 14:21 UTC, gzamudio requested changes

2019-05-13 14:21 UTC, gzamudio commented on src/Views/Movies/Edit.cshtml
> +</form>
add empty line

2019-05-13 14:21 UTC, gzamudio commented on src/Controllers/MoviesController.cs
> +            return RedirectToAction("Index", "Movies");
mmm. i think that if model state is invalid, we should not redirect to index.
if is invalid we must show the errors in the edit view.

2019-05-13 14:21 UTC, gzamudio commented on src/Controllers/MoviesController.cs
> +            if (movie != null)
here we can use:
`if (movie != null)`
`     return View(new MovieViewModel { . . . } );`
`else`
`    return NotFound()`

2019-05-13 14:22 UTC, gzamudio requested changes

2019-05-13 14:22 UTC, gzamudio commented on src/Controllers/MoviesController.cs
> +        [HttpPost("Edit")]
also, i think that the method should be PUT instead of POST.

2019-05-15 13:52 UTC, gzamudio approved these changes

2019-05-16 16:51 UTC, mar7in91Wolox approved these changes

2019-05-16 17:33 UTC, merged