Rating field
wolox-training/ff-net-core pull request #14
Opened 2019-05-14 17:53 UTC by ffasitella

### Summary

- Added a Rating field in class Movie

### Trello card

[https://trello.com/c/qIrcOSYI/11-nueva-propiedad-en-pel%C3%ADcula](https://trello.com/c/qIrcOSYI/11-nueva-propiedad-en-pel%C3%ADcula)

2019-05-22 15:11 UTC, gzamudio approved these changes

2019-05-23 16:28 UTC, mar7in91Wolox requested changes

2019-05-23 16:28 UTC, mar7in91Wolox commented on src/Controllers/MoviesController.cs
> +                UnitOfWork.Movies.Add(new Movie { Title = mvm.Title, ReleaseDate = mvm.ReleaseDate, Genre = mvm.Genre, Price = mvm.Price, Rating = mvm.Rating });
Try to use a constructor in the Movie class :)

2019-05-23 16:28 UTC, mar7in91Wolox commented on src/Controllers/MoviesController.cs
> +                return View(new MovieViewModel { Id = movie.Id, Title = movie.Title, ReleaseDate = movie.ReleaseDate, Genre = movie.Genre, Price = movie.Price, Rating = movie.Rating } );
Idem here, but in the MovieVM class :)

2019-05-23 16:28 UTC, mar7in91Wolox commented on src/Controllers/MoviesController.cs
> +            return View(new MovieViewModel { Title = movie.Title, ReleaseDate = movie.ReleaseDate, Genre = movie.Genre, Price = movie.Price, Rating = movie.Rating } );
Same here and in a few lines below

2019-05-23 17:05 UTC, mar7in91Wolox approved these changes

2019-05-23 17:11 UTC, merged